version: "3.9"
services:
  gro-mongodb:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_ROOT_AUTHENTICATION_DB: ${MONGO_INITDB_ROOT_AUTHENTICATION_DB}
    ports:
      - "${MONGO_INITDB_PORT}:${MONGO_INITDB_PORT}"
    volumes:
      - ./compose/mongodb/data:/data/db
    command: --logpath /dev/null